export default interface IPoultryActivity {
  activityId: number,
  coopId: number,
  employeeId: number,
  day: Date,
  feedBagsUsed: number,
  mediumEggsPicked: number,
  largeEggsPicked: number,
  xLargeEggsPicked: number,
  eggsWashed: number,
  eggsBroken: number,
  nestboxEggs: number,
  floorEggs: number,
  cleanEggs: number,
  dirtyEggs: number,
  mediumEggsPacked: number,
  largeEggsPacked: number,
  xLargeEggsPacked: number,
  manureBags: number,
  chickensDead: number,
  deathReason: string,
  updatedBy: string,
  updatedOn: Date
}