import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import { notificationProvider, RefineSnackbarProvider } from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";

export const metadata: Metadata = {
  title: "FarmWorks",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={notificationProvider}
                    authProvider={authProvider}
                    resources={[
                      {
                        name: "farmworkCategory",
                        list: "/farmworkCategories",
                        create: "/farmworkCategories/create",
                        edit: "/farmworkCategories/edit/:id",
                        show: "/farmworkCategories/show/:id",
                        meta: { 
                          canDelete: true,
                          idName: "categoryId",
                          resources: "farmworksCategory"
                        },
                      }, 
                      {
                        name: "farmwork",
                        list: "/farmworks",
                        create: "/farmworks/create",
                        edit: "/farmworks/edit/:id",
                        show: "/farmworks/show/:id",
                        meta: {
                          canDelete: true,
                          idName: "farmWorkId",
                          resources: "farmworks"
                        },
                      },
                      {
                        name: "employeeRole",
                        list: "/employeeRoles",
                        create: "/employeeRoles/create",
                        edit: "/employeeRoles/edit/:id",
                        show: "/employeeRoles/show/:id",
                        meta: {
                          canDelete: false,
                          idName: "roleId",
                          resources: "employeeRoles"
                        },
                      },
                      {
                        name: "employee",
                        list: "/employees",
                        create: "/employees/create",
                        edit: "/employees/edit/:id",
                        show: "/employees/show/:id",
                        meta: {
                          canDelete: true,
                          idName: "employeeId",
                          resources: "employees"
                        },
                      },
                      {
                        name: "employeeWage",
                        list: "/employeeWages",
                        create: "/employeeWages/create",
                        edit: "/employeeWages/edit/:id",
                        show: "/employeeWages/show/:id",
                        meta: {
                          canDelete: true,
                          idName: "employeeId",
                          resources: "employeeWages"
                        },
                      },
                      {
                        name: "employeeTimeclock",
                        list: "/employeeTimeclocks",
                        create: "/employeeTimeclocks/create",
                        edit: "/employeeTimeclocks/edit/:id",
                        show: "/employeeTimeclocks/show/:id",
                        meta: {
                          canDelete: false,
                          idName: "timeclockId",
                          resources: "employeeTimeclocks"
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "ZVSfsE-ekvuhD-I5VHNv",
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
